hmrc/tax-summaries-frontend

- conf/messages
- test/controllers/ATSMainControllerTest.scala
- test/controllers/AllowancesControllerTest.scala
- test/controllers/CapitalGainsTaxTest.scala
- test/controllers/ErrorControllerTest.scala
- test/controllers/GovernmentSpendControllerTest.scala
- test/controllers/IncomeControllerTest.scala
- test/controllers/NicsSummaryControllerTest.scala
- test/controllers/SummaryControllerTest.scala
- test/controllers/TotalIncomeTaxControllerTest.scala
- test/views/GenericErrorViewTest.scala
- test/views/PortalUserTest.scala
> [TAXS-606] - Content review amends

- project/Microservice.scala
- test/controllers/ATSMainControllerTest.scala
- test/controllers/ErrorControllerTest.scala
- test/controllers/IndexControllerTest.scala
- test/services/AllowanceServiceTest.scala
- test/services/AtsYearListServiceTest.scala
- test/services/CapitalGainsServiceTest.scala
- test/services/GovernmentSpendServiceTest.scala
- test/services/IncomeServiceTest.scala
- test/services/SummaryServiceTest.scala
- test/services/TotalIncomeTaxServiceTest.scala
- test/utils/TaxsUnitTestTraits.scala
- test/utils/prevalidation/PrevalidationTest.scala
[TAXS-642] - Improve Source Coverage Tests
> [TAXS-642] - Improve Source Coverage Tests

- conf/messages
- conf/messages.cy
> [TAXS-592] - Amend messages

- conf/messages.cy
[TAXS-592] - Welsh Translations
> [TAXS-592] - Welsh Translations

- app/controllers/ErrorController.scala
[TAXS-593] - Re-deploy to fix build issue
> [TAXS-593] - Re-deploy to fix build issue

- app/views/government_spending.scala.html
> [TAXS-656] - Tax breakdown

- app/views/total_income_tax.scala.html
[TAXS-657] - Scottish income tax
Only display if incomeTaxStatus = "0002" and value is not zero.
> [TAXS-657] - Scottish income tax

- conf/messages.cy
[TAXS-593] - Welsh Translations for SRIT
> [TAXS-593] - Welsh Translations for SRIT

- app/views/includes/taxs_header_nav.scala.html
- conf/messages
- conf/messages.cy
@danewatts – please can you review my code. Do not merge until after the acceptance tests have been run. Thanks
Apologies for not creating the pull request sooner... My bad.
> DDCNLS-2791 - remove message hardcoding

- conf/messages
- test/views/LanguageAgnosticTest.scala
@Gaur4vGaur – please can you check my code. 
Do not merge until the acceptance tests have been run.
> DDCNLS-2792: Remove contractions (unit tests updated)

- app/controllers/GovernmentSpendController.scala
- app/services/AtsService.scala
- app/services/AtsYearListService.scala
- app/services/GovernmentSpendService.scala
- app/views/government_spending.scala.html
- scalastyle-config.xml
- test/controllers/GovernmentSpendControllerTest.scala
- test/views/LanguageAgnosticTest.scala
- test/views/NonPortalUserTest.scala
- test/views/PortalUserTest.scala
Re-order the 3 keys as per ticket DDCNLS-5246 on government spending page
> Re-order the 3 keys as per ticket DDCNLS-5246

- app/controllers/paye/PayeYourIncomeAndTaxesController.scala
- app/view_models/Amount.scala
- app/view_models/paye/PayeGovernmentSpend.scala
- app/view_models/paye/PayeYourIncomeAndTaxes.scala
- app/views/paye/paye_taxs_main.scala.html
- app/views/paye/paye_your_income_and_taxes.scala.html
- conf/app.routes
- conf/messages
- test/controllers/paye/PayeYourIncomeAndTaxesControllerSpec.scala
- test/resources/paye_ats.json
- test/services/atsData/PayeAtsTestData.scala
- test/view_models/paye/PayeYourIncomeAndTaxesSpec.scala
- test/views/paye/PayeYourIncomeAndTaxesViewSpec.scala
PR for ATS-99 Your income and taxes page
> ATS-99 - Your income and taxes

- conf/messages
Update paragraph to "You do not have an Annual Tax Summary for this year"
> ATS-275 | Amend 'No ATS' copy

- app/views/paye/paye_income_tax_and_nics.scala.html
- app/views/paye/paye_tax_free_amount.scala.html
Adding visually hidden captions to tables to give each table context for screen reader users.
> Adding captions to tables to improve accessibility

- app/services/CryptoService.scala
- test/services/AtsListServiceSpec.scala
- test/services/AtsServiceSpec.scala
- test/services/AtsYearListServiceSpec.scala
- test/services/AuthorityUtilsSpec.scala
- test/services/CryptoServiceSpec.scala
Reverts hmrc/tax-summaries-frontend#111
> Revert "fix longs no longer parsing due to keystore upgrade to bootstrap"

- conf/application.conf
- conf/paye.conf
- test/config/PayeConfigSpec.scala
- test/controllers/paye/PayeYourIncomeAndTaxesControllerSpec.scala
- test/view_models/paye/PayeYourIncomeAndTaxesSpec.scala
Reverts hmrc/tax-summaries-frontend#135
> Revert "DDCNL-1766 | uprating changes for new tax year"

- app/views/errors/PayeServiceUnavailableView.scala.html
- conf/messages
Reverts hmrc/tax-summaries-frontend#178
> Revert "Temporary shutter message"

- app/views/HowTaxIsSpentView.scala.html
- conf/messages
- conf/messages.cy
Reverts hmrc/tax-summaries-frontend#210
> Revert "no ats page text updated"

- conf/application.conf
Reverts hmrc/tax-summaries-frontend#199
> Revert "assets-frontend updated"

- conf/application.conf
Reverts hmrc/tax-summaries-frontend#214
> Revert "Revert "assets-frontend updated""

- app/views/total_income_tax_includes/ScottishTableView.scala.html
Reverts hmrc/tax-summaries-frontend#236
> Revert "DDCNL-4853: table update"

- app/views/total_income_tax_includes/ScottishTableView.scala.html
Reverts hmrc/tax-summaries-frontend#241
> Revert "Revert "DDCNL-4853: table update""
